-- Active: 1680169651631@@localhost@5432@shop@public
-- Generated by the database client, not guaranteed complete.
CREATE TABLE products(
    id integer NOT NULL,
    name character varying(50) NOT NULL,
    description character varying(355) NOT NULL,
    price integer NOT NULL
);
